---
version: '3.7'
services:
  nginx:
    image: defectdojo/defectdojo-nginx:1.19.8-alpine@sha256:e20c21e530f914fb6a95a755924b1cbf71f039372e94ac5ddcf8c3b386a44615
    depends_on:
      - uwsgi
    ports:
      - target: 8443
        published: 443
        protocol: tcp
        mode: host
      - target: 8080
        published: 80
        protocol: tcp
        mode: host
    volumes:
      - /opt/dojo/certs:/etc/nginx/certs
      - /opt/dojo/nginx/nginx.conf:/etc/nginx/nginx.conf
  uwsgi:
    image: defectdojo/defectdojo-django:${DJANGO_VERSION:-latest}
    volumes:
      - type: bind # volume is another, less performant option
        source: /opt/dojo/media
        target: /app/media
    entrypoint: ['/entrypoint-uwsgi.sh']
    environment:
      DD_DEBUG: 'False'
      DD_ALLOWED_HOSTS: ${DD_ALLOWED_HOSTS:-*}
      DD_DATABASE_URL: ${DD_DATABASE_URL}
      DD_CELERY_BROKER_USER: ${DD_CELERY_BROKER_USER:-guest}
      DD_CELERY_BROKER_PASSWORD: ${DD_CELERY_BROKER_USER:-guest}
      DD_SECRET_KEY: ${DD_SECRET_KEY}
      DD_CREDENTIAL_AES_256_KEY: ${DD_CREDENTIAL_AES_256_KEY}
  celerybeat:
    image: defectdojo/defectdojo-django:${DJANGO_VERSION:-latest}
    entrypoint: ['/entrypoint-celery-beat.sh']
    environment:
      DD_DATABASE_URL: ${DD_DATABASE_URL}
      DD_CELERY_BROKER_USER: ${DD_CELERY_BROKER_USER:-guest}
      DD_CELERY_BROKER_PASSWORD: ${DD_CELERY_BROKER_USER:-guest}
      DD_SECRET_KEY: ${DD_SECRET_KEY}
      DD_CREDENTIAL_AES_256_KEY: ${DD_CREDENTIAL_AES_256_KEY}
  celeryworker:
    image: defectdojo/defectdojo-django:${DJANGO_VERSION:-latest}
    entrypoint: ['/entrypoint-celery-worker.sh']
    environment:
      DD_DATABASE_URL: ${DD_DATABASE_URL}
      DD_CELERY_BROKER_USER: ${DD_CELERY_BROKER_USER:-guest}
      DD_CELERY_BROKER_PASSWORD: ${DD_CELERY_BROKER_USER:-guest}
      DD_SECRET_KEY: ${DD_SECRET_KEY}
      DD_CREDENTIAL_AES_256_KEY: ${DD_CREDENTIAL_AES_256_KEY}
  initializer:
    image: defectdojo/defectdojo-django:${DJANGO_VERSION:-latest}
    entrypoint: ['/entrypoint-initializer.sh']
    environment:
      DD_DATABASE_URL: ${DD_DATABASE_URL}
      DD_ADMIN_USER: ${DD_ADMIN_USER:-admin}
      DD_ADMIN_MAIL: ${DD_ADMIN_USER:-admin@defectdojo.local}
      DD_ADMIN_FIRST_NAME: ${DD_ADMIN_FIRST_NAME:-Admin}
      DD_ADMIN_LAST_NAME: ${DD_ADMIN_LAST_NAME:-User}
      DD_INITIALIZE: ${DD_INITIALIZE:-false}
      DD_SECRET_KEY: ${DD_SECRET_KEY}
      DD_CREDENTIAL_AES_256_KEY: ${DD_CREDENTIAL_AES_256_KEY}
  rabbitmq:
    image: rabbitmq:3.7.25@sha256:2e8ebfd211396d0f2d26f1cd540a793904cd5ebbc790ad021a2dbc83aa3aea2a
